### ISSUE TITLE
Does not find License changes

### ISSUE THREAD

**Issue by threehook** [anthonyharrison/sbomdiff#1]

**Comment by threehook** [comment]
Hi Anthony,

I think sbomdiff (latest) does not find license changes.
I have two (initially equal) CycloneDX v.1.4 sboms. When I change one of the license id's in the second bom no license changes are reported.
I think in cyclonedx_parser.py it misses 'evidence' in the loop below line 26.

Below is what I see in my boms:
```
      "evidence": {
        "licenses": [
          {
            "license": {
              "id": "MIT"
            }
          }
        ]
      }
```

Could you please have a look at it. Our intention is to use your tool in our CI/CD pipeline to detect license changes.

Kind Regards,
Ton

**Comment by threehook** [comment]
Hmm, I see there are v1.4 sbom examples with and without an enclosing "evidence" tag around "licenses". Very strange.
I suppose I have to read the specs more thoroughly.

**Comment by anthonyharrison** [comment]
@threehook CycloneDX can specify licences in a number of different ways. I thought I had captured the two ways of specifying a licence. However, having looked at the [CyclonedDX specification](https://cyclonedx.org/docs/1.4/json/#components_items_evidence_licenses) again it would appear that there are two places where a licence can be specified; one at the component level (which is what sbomdiff looks for) and one as evidence (which it doesn't). My understanding of the evidence section is that this is used to capture the outcome of some analysis rather than being the definitive place where a licence is defined. 

I will update sbomdiff to use the evidence section (if present) to extract the licence information if  the license secftion isn't found.
